// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqesdfiomjlccqhjlikn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxZXNkZmlvbWpsY2NxaGpsaWtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MDAwMTksImV4cCI6MjA3MTM3NjAxOX0.yYkFxySsQJcndKidJjGFISKJHBlRza7dxkgb_vUQ4tg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});